services:

  tumbler:
    image: dimalo/klipper-moonraker
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    container_name: tumbler
    ports:
      - 7132:7125
    restart: unless-stopped
    volumes:
      - ./printer_data:/home/klippy/printer_data
      - ./printers/tumbler:/home/klippy/printer_data/config
      - moonraker_data:/home/klippy/.moonraker_database
    devices:
      - /dev/serial/by-id/usb-Klipper_stm32f103xe_33FFD6054252353117882157-if00:/dev/serial/by-id/usb-Klipper_stm32f103xe_33FFD6054252353117882157-if00

  kossel_1:
    image: dimalo/klipper-moonraker
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    container_name: kossel_1
    ports:
      - 7125:7125
    restart: unless-stopped
    volumes:
      - ./printer_data:/home/klippy/printer_data
      - ./variables/kossel_1_variables.cfg:/home/klippy/klipper_variables.cfg
      - ./printers/kossel_1/config:/home/klippy/printer_data/config
      - ./printers/kossel_1/database:/home/klippy/printer_data/database
      - moonraker_data:/home/klippy/.moonraker_database
    devices:
      - /dev/serial/by-id/usb-Klipper_stm32f103xe_33FFD6055641343442671843-if00:/dev/serial/by-id/usb-Klipper_stm32f103xe_33FFD6055641343442671843-if00

  kossel_2:
    image: dimalo/klipper-moonraker
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    container_name: kossel_2
    ports:
      - 7126:7125
    restart: unless-stopped
    volumes:
      - ./printer_data:/home/klippy/printer_data
      - ./variables/kossel_2_variables.cfg:/home/klippy/klipper_variables.cfg
      - ./printers/kossel_2/config:/home/klippy/printer_data/config
      - ./printers/kossel_2/database:/home/klippy/printer_data/database
      - moonraker_data:/home/klippy/.moonraker_databse
    devices:
      - /dev/serial/by-id/usb-Klipper_stm32f103xe_38FFDB055357303903721043-if00:/dev/serial/by-id/usb-Klipper_stm32f103xe_38FFDB055357303903721043-if00

  kossel_3:
    image: dimalo/klipper-moonraker
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    container_name: kossel_3
    ports:
      - 7127:7125
    restart: unless-stopped
    volumes:
      - ./printer_data:/home/klippy/printer_data
      - ./variables/kossel_3_variables.cfg:/home/klippy/klipper_variables.cfg
      - ./printers/kossel_3/config:/home/klippy/printer_data/config
      - ./printers/kossel_3/database:/home/klippy/printer_data/database
      - moonraker_data:/home/klippy/.moonraker_database
    devices:
      - /dev/serial/by-id/usb-Klipper_stm32g0b1xx_06002D000C50345033313820-if00:/dev/serial/by-id/usb-Klipper_stm32g0b1xx_06002D000C50345033313820-if00

  kossel_4:
    image: dimalo/klipper-moonraker
    hostname: kossel_4
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    container_name: kossel_4
    restart: unless-stopped
    ports:
      - 7128:7125
    volumes:
      - ./printer_data:/home/klippy/printer_data
      - ./variables/kossel_4_variables.cfg:/home/klippy/klipper_variables.cfg
      - ./printers/kossel_4/config:/home/klippy/printer_data/config
      - ./printers/kossel_4/database:/home/klippy/printer_data/database
      - moonraker_data:/home/klippy/.moonraker
    devices:
      - /dev/serial/by-id/usb-Klipper_stm32f103xe_33FFDA055641343406612043-if00:/dev/serial/by-id/usb-Klipper_stm32f103xe_33FFDA055641343406612043-if00

  kossel_5:
    image: dimalo/klipper-moonraker
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    container_name: kossel_5
    restart: unless-stopped
    ports:
      - 7129:7125
    volumes:
      - ./printer_data:/home/klippy/printer_data
      - ./variables/kossel_5_variables.cfg:/home/klippy/klipper_variables.cfg
      - ./printers/kossel_5/config:/home/klippy/printer_data/config
      - ./printers/kossel_5/database:/home/klippy/printer_data/database
      - moonraker_data:/home/klippy/.moonraker_database
    devices:
      - /dev/serial/by-id/usb-Klipper_stm32f103xe_38FFD4055357303916881043-if00:/dev/serial/by-id/usb-Klipper_stm32f103xe_38FFD4055357303916881043-if00

  ender3_1:
    image: dimalo/klipper-moonraker
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    container_name: ender3_1
    ports:
      - 7130:7125
    volumes:
      - /dev/:/dev/
      - ./printer_data:/home/klippy/printer_data
      - ./variables/ender3_1_variables.cfg:/home/klippy/klipper_variables.cfg
      - ./printers/ender3_1/config:/home/klippy/printer_data/config
      - ./printers/ender3_1/database:/home/klippy/printer_data/database
      - moonraker_data:/home/klippy/.moonraker_database
    devices:
      - /dev/serial/by-id/usb-Klipper_stm32g0b1xx_410029000450415339373620-if00:/dev/serial/by-id/usb-Klipper_stm32g0b1xx_410029000450415339373620-if00

  ender3_2:
    image: dimalo/klipper-moonraker
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    container_name: ender3_2
    ports:
      - 7131:7125
    volumes:
      - /dev/:/dev/
      - ./printer_data:/home/klippy/printer_data
      - ./variables/ender3_2_variables.cfg:/home/klippy/klipper_variables.cfg
      - ./printers/ender3_2/config:/home/klippy/printer_data/config
      - ./printers/ender3_2/database:/home/klippy/printer_data/database
      - moonraker_data:/home/klippy/.moonraker_database
    devices:
      - /dev/serial/by-path/ender3_2_device_link:/dev/serial/by-path/ender3_2_device_link

  fluidd:
    image: dimalo/fluidd
    # build:
    #   dockerfile: Dockerfile
    #   context: frontend
    # stdin_open: true # docker run -i
    # tty: true        # docker run -
    container_name: fluidd
    environment:
      - KLIPPER_HOST=kossel_1
    # depends_on:
    #   - ender3_1
    # links:
    #   - kossel_5:kossel_5
    #   - kossel_4:kossel_4
    volumes:
      - ./config:/home/klippy/printer_data/config
      - ./moonraker_database:/home/klippy/.moonraker_database
    ports:
      - 8010:80

volumes:
  variables:
  printer_data:
  gcode_files:
  moonraker_data:

